'use strict';
const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const root=path.join(__dirname,'..');
const server=fs.readFileSync(path.join(root,'server.js'),'utf8');
const storage=fs.readFileSync(path.join(root,'lib/google-sheets-storage.js'),'utf8');
const gas=fs.readFileSync(path.join(root,'google-apps-script/Code.gs'),'utf8');
const pkg=require('../package.json');
assert.equal(pkg.version,'28.25.0');
assert.equal(pkg.scripts.start,'node server.js');
assert.match(server,/google-sheets-storage/);
assert.match(server,/const VERSION = '28\.25'/);
assert.doesNotMatch(server,/require\('\.\/lib\/postgres-storage'\)/);
assert.match(storage,/GOOGLE_SPREADSHEET_ID/);
assert.match(storage,/GOOGLE_SHEETS_WEBAPP_URL/);
assert.match(storage,/GOOGLE_SHEETS_API_SECRET/);
assert.doesNotMatch(storage,/GOOGLE_SERVICE_ACCOUNT_EMAIL/);
assert.doesNotMatch(storage,/GOOGLE_PRIVATE_KEY/);
assert.doesNotMatch(storage,/oauth2\.googleapis\.com/);
assert.match(storage,/upsertMany/);
assert.match(storage,/readMany/);
for(const tab of ['Leads','LeadEvents','Notifications','Outbox','SLASettings','NotificationRules','Managers','Statuses','Users','Bootstrap','Runtime'])assert.match(storage,new RegExp(tab));
assert.match(gas,/function doPost/);
assert.match(gas,/LockService\.getScriptLock/);
assert.match(gas,/action === 'upsertMany'/);
assert.match(gas,/action === 'readMany'/);
assert.match(gas,/SPREADSHEET_ID = '1lm0ajA6nFpQ5jXybxm3MY5pVp0gTjqP_oC_0rira7oI'/);
console.log('v28.25 integration checks: OK (Apps Script Web App + Google Sheets, no PostgreSQL/Cloud Console)');
