'use strict';
const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const root=path.join(__dirname,'..');
const server=fs.readFileSync(path.join(root,'server.js'),'utf8');
const storage=fs.readFileSync(path.join(root,'lib/google-sheets-storage.js'),'utf8');
const pkg=require('../package.json');
assert.equal(pkg.version,'28.24.0');
assert.equal(pkg.scripts.start,'node server.js');
assert.match(server,/google-sheets-storage/);
assert.match(server,/const VERSION = '28\.24'/);
assert.doesNotMatch(server,/require\('\.\/lib\/postgres-storage'\)/);
assert.match(storage,/GOOGLE_SPREADSHEET_ID/);
assert.match(storage,/GOOGLE_SERVICE_ACCOUNT_EMAIL/);
assert.match(storage,/GOOGLE_PRIVATE_KEY/);
for(const tab of ['Leads','LeadEvents','Notifications','Outbox','SLASettings','NotificationRules','Managers','Statuses','Users','Bootstrap','Runtime'])assert.match(storage,new RegExp(tab));
assert.match(storage,/async upsertLeadJournalBatch/);
assert.match(storage,/async getNotificationHistoryRows/);
assert.match(storage,/async saveSession/);
assert.match(storage,/async claimCreate/);
console.log('v28.24 integration checks: OK (Google Sheets storage, no PostgreSQL runtime)');
