'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert');
const ROOT=path.join(__dirname,'..');
const server=fs.readFileSync(path.join(ROOT,'server.js'),'utf8');
const app=fs.readFileSync(path.join(ROOT,'public','app.js'),'utf8');
const api=fs.readFileSync(path.join(ROOT,'public','api.js'),'utf8');
const css=fs.readFileSync(path.join(ROOT,'public','styles.css'),'utf8');
const render=fs.readFileSync(path.join(ROOT,'render.yaml'),'utf8');
assert(/const VERSION = '25\.[12]'/.test(server));
assert(server.includes('admin_author_id'),'VK admin author attribution missing');
assert(server.includes('seb_gun_crm:{author:'),'CRM author payload marker missing');
assert(server.includes('audioMessageFromDoc'),'doc.preview.audio_msg voice normalization missing');
assert(server.includes('/messages\\/(\\d+)\\/transcript'),'voice transcript refresh endpoint missing');
assert(server.includes("customers.addMany"),'BlueSales addMany fallback missing');
assert(server.includes('recoveredFromUpstreamError'),'BlueSales post-error duplicate recovery missing');
assert(server.includes("const includeCrm = String(url.searchParams.get('crm') || '1') !== '0'"),'fast VK dialog mode missing');
assert(api.includes('includeCrm=true'),'dialog CRM loading switch missing');
assert(app.includes('hydrateDialogCrmSlice'),'background CRM hydration missing');
assert(app.includes('data-msg-menu'),'VK-like message menu missing');
assert(app.includes('data-msg-copy-transcript'),'copy transcript action missing');
assert(app.includes('messageAuthorLabel'),'message author label missing');
assert(api.includes('vkTranscript:'),'transcript API client missing');
assert(css.includes('.msg-action-menu'),'message action menu styles missing');
assert(render.includes('ALLOW_LOCAL_PHRASE_FALLBACK\n        value: "1"'),'quick phrase fallback not enabled');
assert(render.includes('VK_DIRECT_AUTHOR'),'direct VK author fallback missing');
console.log('v25.1 integration checks: OK');
