'use strict';
const fs=require('fs');
const path=require('path');
const vm=require('vm');
const root=path.resolve(__dirname,'..');
const server=fs.readFileSync(path.join(root,'server.js'),'utf8');
const app=fs.readFileSync(path.join(root,'public','app.js'),'utf8');
const api=fs.readFileSync(path.join(root,'public','api.js'),'utf8');
const phrases=JSON.parse(fs.readFileSync(path.join(root,'data','quick_phrases.json'),'utf8'));
const total=(phrases.groups||[]).reduce((n,g)=>n+(g.phrases||[]).length,0);
const media=(phrases.groups||[]).flatMap(g=>g.phrases||[]).flatMap(p=>p.attachments||[]);
if(total<100) throw new Error(`unexpected phrase total ${total}`);
if(!media.some(x=>String(x).startsWith('photo'))) throw new Error('photo phrase attachments missing');
if(!media.some(x=>String(x).startsWith('audio_message'))) throw new Error('audio_message phrase attachments missing');
if(!server.includes("const g=ensurePhraseGroup(store,target);\n      found.group.phrases.splice(found.index,1);")) throw new Error('phrase move/update ordering fix missing');
if(!server.includes('attachmentRe=/\\[((?:photo|video|doc|audio_message)')) throw new Error('attachment token extraction missing');
if(!api.includes('deleteReminder:')) throw new Error('reminder delete API missing');
if(!server.includes("req.method==='DELETE'")) throw new Error('reminder DELETE route missing');
if(!app.includes("state.meta.users||[]")) throw new Error('all-manager source missing');
if(!app.includes('refreshPhraseListOnly()')) throw new Error('non-destructive phrase search missing');
if(!app.includes('refreshPhraseAutocomplete()')) throw new Error('non-destructive composer phrase search missing');
if(!app.includes("q.length<1")) throw new Error('first-character phrase search missing');
if(!app.includes('data-copy-route')) throw new Error('deep/share links missing');
if(!app.includes('data-remove-reminder')) throw new Error('reminder remove button missing');
if(!app.includes("window.addEventListener('hashchange'")) throw new Error('deep-link routing missing');
console.log('OK: v24.0 phrase edit persistence + media attachment extraction');
console.log('OK: stable left-to-right searches + phrase autocomplete from first character');
console.log('OK: all BlueSales managers are used in filters');
console.log('OK: reminder remove + client/tab/dialog deep links');
console.log(`OK: phrase source contains ${total} rows and ${media.length} media attachments`);
