'use strict';
const fs=require('fs'),path=require('path');
const root=path.join(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8'),pkg=require('../package.json');
const server=read('server.js'),api=read('frontend/src/services/api.js'),app=read('frontend/src/App.vue'),sla=read('frontend/src/views/ManagersView.vue'),history=read('frontend/src/views/NotificationHistoryView.vue'),more=read('frontend/src/views/MoreView.vue');
function must(v,m){if(!v)throw new Error(m)}
must(['28.21.0','28.22.0'].includes(pkg.version)&&/const VERSION = '28\.(21|22)'/.test(server),'version mismatch');
must((app.match(/api\.bootstrapDialogsOnce\(\)/g)||[]).length===1,'bootstrap starts more than once in App');
must(api.includes('apiCooldownUntil')&&api.includes('[429, 502, 503, 504].includes(response.status)')&&api.includes('retryAfterMs'),'API cooldown/backoff missing');
must(api.includes("bootstrapDialogsStatus: () => request('/api/bootstrap/dialogs-once', { timeout:15000, retries:1, retryDelay:3000 })"),'bootstrap status is still no-dedupe/no-backoff');
must(server.includes('async function vkCallPolite')&&server.includes("loadDialogBootstrapPage(session,offset,100)")&&(server.includes('offset-lastPersisted>=25')||server.includes('offset-lastProgressPersisted>=25')),'paced incremental bootstrap missing');
const bootstrapBlock=server.slice(server.indexOf('async function runDialogBootstrapOnce'),server.indexOf('function startDialogBootstrapOnce'));
must(!bootstrapBlock.includes('Promise.all('),'parallel VK history burst still present in one-time bootstrap');
must(server.includes("status:'paused_rate_limit'")&&server.includes('retryAt'),'VK rate-limit pause/resume missing');
must(sla.includes('window.setTimeout(pollBootstrap,8000)')&&sla.includes('let delay=12000')&&sla.includes('pollFailures'),'SLA polling backoff missing');
must(history.includes('let delay=15000')&&history.includes('pollFailures'),'notification-history polling backoff missing');
must(more.includes('window.setTimeout(poll,15000)')&&more.includes('withHistory:pollCount.value%4===0'),'More polling is still too aggressive');
must(server.includes('scheduleHistoricalNotificationBackfill')&&(server.includes('allRows.slice(0,1500)')||server.includes('getNotificationHistoryRows({names,admin,limit:1500})')),'history GET still performs synchronous backfill or unbounded response');
must((server.includes('sortedRows.slice(0,2000)')||server.includes('visibleLimit:2000')),'SLA response is unbounded');
must(server.includes("immutableAsset ? 'public, max-age=31536000, immutable'"),'hashed asset caching missing');
console.log('v28.21 integration checks: OK (Render/VK backpressure, incremental bootstrap, lightweight polling, bounded reports)');
