'use strict';
const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const root=path.join(__dirname,'..');
const server=fs.readFileSync(path.join(root,'server.js'),'utf8');
const storage=fs.readFileSync(path.join(root,'lib/google-sheets-storage.js'),'utf8');
const gas=fs.readFileSync(path.join(root,'google-apps-script/Code.gs'),'utf8');
const drawer=fs.readFileSync(path.join(root,'frontend/src/components/ClientDrawer.vue'),'utf8');
const css=fs.readFileSync(path.join(root,'frontend/src/assets/base.css'),'utf8');
const pkg=require('../package.json');
assert.equal(pkg.version,'28.26.0');
assert.equal(pkg.scripts.start,'node server.js');
assert.match(server,/google-sheets-storage/);
assert.match(server,/const VERSION = '28\.26'/);
assert.match(server,/\.okcdn\.ru/);
assert.match(server,/Render hits this endpoint frequently/);
assert.doesNotMatch(server,/require\('\.\/lib\/postgres-storage'\)/);
assert.match(storage,/storage_version',value:'28\.26'/);
assert.match(storage,/materializeLead/);
assert.match(storage,/eventSignature/);
assert.match(storage,/SLASettings/);
assert.match(storage,/Bootstrap/);
assert.match(storage,/GOOGLE_SHEETS_WEBAPP_URL/);
assert.doesNotMatch(storage,/GOOGLE_SERVICE_ACCOUNT_EMAIL/);
assert.doesNotMatch(storage,/GOOGLE_PRIVATE_KEY/);
assert.match(gas,/TEXT_COLUMNS/);
assert.match(gas,/migrateTextColumns/);
assert.match(gas,/storageVersion: '28\.26'/);
assert.match(drawer,/function dateInputValue/);
assert.match(drawer,/crm-accordion-card/);
assert.match(drawer,/client-mobile-actions/);
assert.match(drawer,/picker='date'/);
assert.match(drawer,/type="date"/);
assert.match(css,/@media\(max-width:760px\)/);
assert.match(css,/client-card-v2826/);
console.log('v28.26 integration checks: OK (Sheets SLA fixes + responsive client card + OK CDN preview)');
