const fs=require('fs');
const assert=require('assert');
const app=fs.readFileSync('public/app.js','utf8');
const css=fs.readFileSync('public/styles.css','utf8');
const sw=fs.readFileSync('public/sw.js','utf8');
const index=fs.readFileSync('public/index.html','utf8');
const server=fs.readFileSync('server.js','utf8');
const pkg=JSON.parse(fs.readFileSync('package.json','utf8'));
const phrases=JSON.parse(fs.readFileSync('data/quick_phrases.json','utf8'));
assert.equal(pkg.version,'27.0.0');
assert(app.includes("MESSAGE_DRAFT_STORAGE='seb_gun_message_draft_v2'"));
assert(app.includes('data-draft-rev'));
assert(app.includes('reconcileStoredMessageDraft'));
assert(app.includes('continueDialogLoadInBackground'));
assert(app.includes('dialogs-first-page'));
assert(app.includes('Mobile v27 never rebuilds the entire conversation'));
assert(app.includes('data-multi-close'));
assert(css.includes('v27.0 — stable mobile kernel'));
assert(css.includes('position:fixed!important'));
assert(css.includes('height:min(72dvh,620px)!important'));
assert(css.includes('position:sticky!important'));
assert(css.includes('env(safe-area-inset-bottom)'));
assert(server.includes('sealSessionSnapshot'));
assert(server.includes('unsealSessionSnapshot'));
assert(server.includes('sessionResume:true'));
assert(server.includes("const VERSION = '27.0'"));
assert(sw.includes('v27.0.0'));
assert(index.includes('app.js?v=27.0.0'));
const count=(phrases.groups||[]).reduce((n,g)=>n+(g.phrases||[]).length,0);
assert(count>=151,`expected >=151 phrases, got ${count}`);
console.log(`v27.0 integration checks: OK (${count} phrases)`);
