'use strict';
const assert=require('node:assert/strict'),fs=require('fs'),path=require('path');
const root=path.join(__dirname,'..');
const pkg=JSON.parse(fs.readFileSync(path.join(root,'package.json'),'utf8'));
const wrapper=fs.readFileSync(path.join(root,'server-v2823.js'),'utf8');
const eventStore=fs.readFileSync(path.join(root,'lib/event-state-store.js'),'utf8');
assert.equal(pkg.scripts.start,'node server-v2823.js');
assert.match(pkg.scripts['check:runtime'],/server-v2823\.js/);
assert.match(pkg.scripts['check:runtime'],/event-state-store\.js/);
assert.match(pkg.scripts['test:v2819'],/integration-v2823\.js/);
assert.match(pkg.scripts['test:database'],/event-state-v2823\.js/);
assert.match(wrapper,/getSlaProjectionReport/);
assert.match(wrapper,/getNotificationHistorySummaryCached/);
assert.match(wrapper,/event-log-state/);
assert.match(wrapper,/const VERSION = '28\.23'/);
assert.doesNotMatch(wrapper,/scanLeadJournal\(/);
assert.match(eventStore,/CREATE TABLE IF NOT EXISTS crm_event_log/);
assert.match(eventStore,/CREATE TABLE IF NOT EXISTS lead_state/);
assert.match(eventStore,/event_projection_state/);
assert.match(eventStore,/ON CONFLICT\(dedupe_key\) DO NOTHING/);
assert.match(eventStore,/lead_events_cursor/);
assert.match(eventStore,/lead_state_backfill/);
assert.match(eventStore,/event-state-materialized/);
console.log('v28.23 integration checks: OK (append-only event log, materialized lead state, read-only SLA/history paths)');
