'use strict';
const fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..');
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const server=read('server.js'),pkg=JSON.parse(read('package.json'));
const chat=read('frontend/src/views/ChatView.vue'),bubble=read('frontend/src/components/MessageBubble.vue');
const clients=read('frontend/src/stores/clients.js'),clientView=read('frontend/src/views/ClientsView.vue');
const clientDrawer=read('frontend/src/components/ClientDrawer.vue'),dialogs=read('frontend/src/views/DialogsView.vue');
const reminders=read('frontend/src/views/RemindersView.vue'),sheet=read('frontend/src/components/MultiFilterSheet.vue');
const api=read('frontend/src/services/api.js'),css=read('frontend/src/assets/base.css'),phrases=read('frontend/src/stores/phrases.js');
if(!server.includes("const VERSION = '28.2'")||pkg.version!=='28.2.0')throw new Error('version mismatch');
if(!css.includes('@media(min-width:1100px)')||!css.includes('--workspace-left')||!css.includes('.client-drawer-backdrop .side-drawer'))throw new Error('desktop pinned workspace missing');
if(!css.includes('.message-scroller::-webkit-scrollbar')||!css.includes('scrollbar-color'))throw new Error('visible chat scrollbar missing');
if(!clientDrawer.includes('crm-classic-stack')||!clientDrawer.includes('statusStyle(meta')||!clientDrawer.includes('managerStyle(meta'))throw new Error('classic colorful CRM card missing');
if(!chat.includes('copyWholeDialog')||!api.includes('dialogText:')||!bubble.includes('messageText(props.message)'))throw new Error('dialog/message copy missing');
if(!server.includes('Copying must never start speech recognition'))throw new Error('dialog export can still start STT');
if(!clients.includes("limit: 100, offset")||clients.includes('while (++guard'))throw new Error('clients still auto-scan thousands of rows');
if(!clientView.includes('value:u.login||u.name')||!reminders.includes('value:u.login||u.name'))throw new Error('manager filter must send BlueSales login');
if(!server.includes(':clients-manager:')||!api.includes("clients: (params = {}) => request(`/api/clients?${query(params)}`, { timeout: 45000 })"))throw new Error('BlueSales request cache/dedupe missing');
if(!dialogs.includes("query:{from:route.fullPath}")||!clientView.includes("query:{from:route.fullPath}")||!reminders.includes("query:{from:route.fullPath}"))throw new Error('return route missing');
if(!dialogs.includes('listQuery(')||!clientView.includes('listQuery(')||!reminders.includes('listQuery('))throw new Error('filter URL state missing');
if(sheet.includes('autofocus'))throw new Error('autofocus warning still present');
if(!api.includes("kind: 'image'")||!server.includes("'X-Media-Fallback':'1'"))throw new Error('safe image fallback missing');
if(!phrases.includes('let hasCache = false'))throw new Error('instant phrase cache missing');
console.log('v28.2 integration checks: OK (responsive workspace, copy, route state, color CRM, media fallback, paged BlueSales)');
