'use strict';
const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const root=path.join(__dirname,'..');
const server=fs.readFileSync(path.join(root,'server.js'),'utf8');
const storage=fs.readFileSync(path.join(root,'lib/google-sheets-storage.js'),'utf8');
const gas=fs.readFileSync(path.join(root,'google-apps-script/Code.gs'),'utf8');
const more=fs.readFileSync(path.join(root,'frontend/src/views/MoreView.vue'),'utf8');
const pkg=require('../package.json');
assert.equal(pkg.version,'28.27.0');
assert.match(server,/const VERSION = '28\.27'/);
assert.match(server,/monthly analytics bootstrap/);
assert.match(server,/loadDialogMessagesForAnalyticsPeriod/);
assert.match(server,/cachedClients\?\./);
assert.match(server,/source:'google-cache'/);
assert.match(server,/\/api\/admin\/monthly\/start/);
assert.match(server,/startCurrentMonth/);
assert.doesNotMatch(server,/const linked=await getCustomersByVkIds\(session,vkIds\),byVk=.*bootstrap crm link/);
assert.match(storage,/QuickPhrases/);
assert.match(storage,/ClientsCache/);
assert.match(storage,/analytics_period/);
assert.match(storage,/rotation_required/);
assert.match(storage,/MONTHLY_AUTO_PREPARE/);
assert.match(storage,/\['Leads','LeadEvents','Notifications','Outbox','Bootstrap'\]/);
assert.match(storage,/seedQuickPhrasesFromLocal/);
assert.match(storage,/cachedClientsByVkIds/);
assert.match(storage,/storage_version',value:'28\.27'/);
assert.match(gas,/storageVersion: '28\.27'/);
assert.match(gas,/ACTIVE_SPREADSHEET_ID/);
assert.doesNotMatch(gas,/Spreadsheet ID mismatch/);
assert.match(more,/Новый месяц аналитики/);
assert.match(more,/v28\.27/);
assert.match(more,/Очистить аналитику в НОВОЙ таблице и начать месяц/);
console.log('v28.27 integration checks: OK (monthly analytics + phrase sheet + client cache fallback)');
