'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert');
const ROOT=path.join(__dirname,'..');
const server=fs.readFileSync(path.join(ROOT,'server.js'),'utf8');
const app=fs.readFileSync(path.join(ROOT,'public','app.js'),'utf8');
const api=fs.readFileSync(path.join(ROOT,'public','api.js'),'utf8');
const css=fs.readFileSync(path.join(ROOT,'public','styles.css'),'utf8');
const render=fs.readFileSync(path.join(ROOT,'render.yaml'),'utf8');
assert(server.includes("const VERSION = '25.2'"));
assert(server.includes('transcribeVoiceExternal'),'external STT fallback missing');
assert(server.includes('whisper-large-v3-turbo'),'Whisper model default missing');
assert(server.includes('voiceTranscriptCache'),'transcript cache missing');
assert(render.includes('GROQ_API_KEY'),'Groq Render secret missing');
assert(app.includes('PHRASE_DRAWER_STORAGE'),'persistent phrase drawer missing');
assert(app.includes('phrase-current'),'last phrase highlight missing');
assert(app.includes('bindChatSwipeGestures'),'mobile swipe drawer gestures missing');
assert(app.includes('textMatchesQuery(`${g.name} ${p.name} ${p.text}`,q)'),'phrase content search missing');
assert(app.includes("setInterval(poll,45000)"),'reduced polling pressure missing');
assert(api.includes('inflightGet'),'GET request de-duplication missing');
assert(api.includes('cacheMs:300000'),'services client cache missing');
assert(css.includes('.bs-phrase-row.phrase-current'),'phrase position CSS missing');
console.log('v25.2 integration checks: OK');
