'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert');
const ROOT=path.resolve(__dirname,'..');
const app=fs.readFileSync(path.join(ROOT,'public','app.js'),'utf8');
const server=fs.readFileSync(path.join(ROOT,'server.js'),'utf8');
const pkg=require(path.join(ROOT,'package.json'));
assert(server.includes("const VERSION = '24.5'"),'v24.5 server version missing');
assert(server.includes("perf: { mode:'fast-meta', customerScan:false }"),'fast metadata mode missing');
const metaBlock=server.slice(server.indexOf("pathname === '/api/meta'"),server.indexOf("pathname === '/api/clients'"));
assert(!metaBlock.includes('getAllCustomers('),'meta must not scan all customers');
assert(server.includes("const cacheKey = `${s.login}:orders:${customerId || 0}:${limit}:${offset}`"),'orders GET cache missing');
assert(server.includes('clearOrdersCache(s.login, customerId)'),'targeted order cache invalidation missing');
assert(server.includes('[BlueSales queue]'),'queue wait diagnostics missing');
assert(app.includes('metaPromise:null'),'client meta promise dedupe missing');
assert(app.includes('servicePromise:null'),'client services promise dedupe missing');
assert(app.includes('drawerOrdersPromise:null'),'client orders promise dedupe missing');
assert(app.includes('Promise.allSettled([ensureServices(),ensureMeta()])'),'new order must open before metadata finishes');
assert(app.includes('refreshServiceResultsOnly()'),'service search must refresh only service results');
assert(app.includes('loadDrawerOrders(true).catch(()=>{})'),'order save must refresh in background');
assert(pkg.version==='24.5.0','package version missing');
console.log('OK: v24.5 fast metadata + cached orders + responsive service picker.');
