'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert');
const root=path.join(__dirname,'..');
const app=fs.readFileSync(path.join(root,'public','app.js'),'utf8');
const server=fs.readFileSync(path.join(root,'server.js'),'utf8');
const css=fs.readFileSync(path.join(root,'public','styles.css'),'utf8');
const phrases=JSON.parse(fs.readFileSync(path.join(root,'data','quick_phrases.json'),'utf8'));
const phraseCount=(phrases.groups||[]).reduce((n,g)=>n+(g.phrases||[]).length,0);
assert(phraseCount>=140,'phrase export unexpectedly small');
assert(app.includes("hydrateChatClient(true)"),'edit must fetch full client');
assert(app.includes("window.innerWidth>=1100"),'desktop breakpoint missing');
assert(app.includes("seb_gun CRM"),'brand missing');
assert(app.includes("seb_gun_theme"),'theme persistence missing');
assert(app.includes("peer=x.peer||{}"),'deep-link fallback peer missing');
assert(app.includes("state.phraseLoaded&&!state.phraseGroups.length"),'phrase export must override stale capability');
assert(server.includes("let peer = { peerId"),'message history must return peer metadata');
assert(server.includes('searchConversations')&&server.includes('sortDialogsBySearchScore'),'hybrid dialog search missing');
assert(css.includes('[data-theme="dark"]'),'dark theme missing');
assert(css.includes('@media(min-width:1100px)'),'desktop three-column layout missing');
console.log('OK: v24 full-client edit hydration + date-safe edit flow.');
console.log('OK: direct #/dialog links no longer depend on first dialog page.');
console.log('OK: quick phrases auto-load on desktop and use the account-filtered export.');
console.log('OK: hybrid VK + BlueSales search and seb_gun light/dark responsive workspace.');
