'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert');
const root=path.resolve(__dirname,'..');
const server=fs.readFileSync(path.join(root,'server.js'),'utf8');
const app=fs.readFileSync(path.join(root,'public','app.js'),'utf8');
const api=fs.readFileSync(path.join(root,'public','api.js'),'utf8');
const render=fs.readFileSync(path.join(root,'render.yaml'),'utf8');
const pkg=JSON.parse(fs.readFileSync(path.join(root,'package.json'),'utf8'));
assert(server.includes("const VERSION = '25.4'"));
assert(server.includes("'/api/stt/transcribe'"));
assert(server.includes('transcribeVoiceLocal'));
assert(server.includes('local-stt-worker.mjs'));
assert(!server.includes('GROQ_API_KEY'));
const sttRoute=server.slice(server.indexOf("if (pathname === '/api/stt/transcribe'"),server.indexOf("if (vkMessagesMatch && req.method === 'POST')"));
assert(sttRoute.includes('transcribeVoiceLocal'));
assert(!sttRoute.includes('vkCall('));
assert(!sttRoute.includes('messages.getByConversationMessageId'));
assert(!server.includes('refreshMissingVoiceTranscripts'));
assert(api.includes('transcribeVoice:'));
assert(!api.includes('vkTranscript:'));
assert(app.includes('BSAPI.transcribeVoice'));
assert(app.includes("const PHRASE_DRAWER_STORAGE='seb_gun_phrase_drawer_v4'"));
assert(app.includes('bindChatSwipeGestures'));
assert(app.includes("window.addEventListener('popstate',handleHistoryRoute)"));
assert(app.includes("window.addEventListener('hashchange',handleHistoryRoute)"));
assert(app.includes('textMatchesQuery(`${g.name} ${p.name} ${p.text}`'));
assert(app.includes('phraseDrawerStorageKey'));
assert(app.includes('mobile-edge-handle'));
assert(app.includes("setInterval(poll,60000)"));
assert(pkg.dependencies['@huggingface/transformers']);
assert(pkg.dependencies['audio-decode']);
assert(render.includes('npm install --omit=dev'));
assert(render.includes('LOCAL_STT_MODEL'));
assert(!render.includes('GROQ_API_KEY'));
assert(fs.existsSync(path.join(root,'lib','local-stt-worker.mjs')));
console.log('integration-v254: OK');
