const fs=require('fs'),path=require('path'),assert=require('assert');
const R=path.join(__dirname,'..');
const s=fs.readFileSync(path.join(R,'server.js'),'utf8');
const a=fs.readFileSync(path.join(R,'public','app.js'),'utf8');
const c=fs.readFileSync(path.join(R,'public','styles.css'),'utf8');
assert(s.includes("const VERSION = '26.9'"));
assert(s.includes('const APP_TIMEZONE'));
assert(s.includes('reminderBucketFor'));
assert(s.includes("source:'customers.get-nextContactDate-range+crm-clock'"));
assert(s.includes('clock: appClockPayload()'));
assert(a.includes('function syncCrmClock'));
assert(a.includes('function snapshotComposerDraft'));
assert(a.includes('data-peer-id="${esc(d.peerId)}"'));
assert(a.includes('Скрипт сохранён в черновике'));
assert(a.includes('crm-clock-line'));
assert(a.includes('refreshMessageFlowKeepPosition'));
assert(s.includes('clock:appClockPayload()'));
assert(!a.includes('[50,120,260,520,900,1400,2100]'));
assert(c.includes('v26.9: one viewport-safe control system'));
console.log('v26.9 integration checks: OK');
