'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert');
const ROOT=path.join(__dirname,'..');
const read=(p)=>fs.readFileSync(path.join(ROOT,p),'utf8');
const server=read('server.js');
const app=read('public/app.js');
const api=read('public/api.js');
const css=read('public/styles.css');
const render=read('render.yaml');
const pkg=JSON.parse(read('package.json'));
assert(server.includes("const VERSION = '25.3'"),'v25.3 server version missing');
assert(server.includes("direct.append('url'"),'direct STT URL path missing');
assert(server.includes('downloadVoiceForStt(audioUrl)'),'STT upload fallback missing');
assert(server.includes('transcribeMissingVoiceMessages'),'full-dialog voice transcription helper missing');
assert(server.includes('voiceTranscribed'),'voice export counters missing');
assert(server.includes('API_TIMEOUT_MS || 18000'),'shorter API timeout missing');
assert(app.includes("PHRASE_DRAWER_STORAGE='seb_gun_phrase_drawer_v3'"),'phrase drawer v3 persistence missing');
assert(app.includes('phraseResumeHtml'),'resume/recent scripts UI missing');
assert(app.includes('phraseRecentIds'),'recent scripts state missing');
assert(app.includes('openChatDrawer'),'unified drawer history missing');
assert(app.includes("overlay=side==='phrases'?'phrases':'crm'")&&app.includes("history.state?.overlay"),'drawer History API state missing');
assert(app.includes('bindChatSwipeGestures'),'mobile edge swipes missing');
assert(app.includes('loadingWatchdog=setTimeout'),'loading watchdog missing');
assert(app.includes('},32000)'),'stuck loading timeout missing');
assert(app.includes('scheduleDialogCrmHydration'),'deferred BlueSales dialog hydration missing');
assert(api.includes('staleMs'),'stale-cache fallback missing');
assert(api.includes('staleUntil'),'stale cache expiry missing');
assert(api.includes('cacheMs:1800000'),'services long cache missing');
assert(render.includes('GROQ_API_KEY'),'Groq secret declaration missing');
assert(render.includes('API_TIMEOUT_MS')&&render.includes('BS_QUEUE_MAX_WAIT_MS'),'Render performance settings missing');
assert(css.includes('.phrase-resume-panel'),'resume scripts CSS missing');
assert(pkg.version==='25.3.0','package version must be 25.3.0');
console.log('v25.3 integration checks: OK');
