<script setup>
import { computed, onMounted, reactive, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { api } from '../services/api'
import { useSessionStore } from '../stores/session'
import { useUiStore } from '../stores/ui'
import { VK_ATTACHMENT_TYPES, attachmentMeta, normalizeVkAttachment } from '../utils/vkAttachments'
import MultiFilterSheet from '../components/MultiFilterSheet.vue'

const route=useRoute(),router=useRouter(),session=useSessionStore(),ui=useUiStore()
const loading=ref(false),query=ref(''),overview=ref(null),groups=ref([]),users=ref([]),sections=ref([]),statuses=ref([]),notificationRows=ref([])
const phraseEditor=ref(false),sectionEditor=ref(false),sectionName=ref(''),userEditor=ref(false),saving=ref(false),editingPhrase=ref(null),editingUser=ref(null),moveTarget=ref(''),managersPicker=ref(false)
const phraseForm=reactive({groupName:'',name:'',text:'',hotkey:'',managers:[],attachments:[]})
const attachmentType=ref('photo'),attachmentInput=ref('')
const selectedAttachmentType=computed(()=>VK_ATTACHMENT_TYPES.find(x=>x.id===attachmentType.value)||VK_ATTACHMENT_TYPES[0])
const userForm=reactive({role:'manager',status:'active',color:'#2f7d55',sections:[]})
const slaForm=reactive({workDays:[1,2,3,4,5],workStart:'10:00',workEnd:'22:00',notifyMinutes:8,violationMinutes:20,timezone:'Europe/Moscow',notifyWeb:true,notifyTelegram:true,violationAction:'journal',managerSchedules:{}})
const weekDays=[[1,'Пн'],[2,'Вт'],[3,'Ср'],[4,'Чт'],[5,'Пт'],[6,'Сб'],[0,'Вс']]
const section=computed(()=>['phrases','users','statuses','notifications','sla'].includes(String(route.params.section))?String(route.params.section):'phrases')
const groupNames=computed(()=>groups.value.map(g=>g.name))
const managerNames=computed(()=>users.value.map(u=>u.name||u.login).filter(Boolean))
const managerOptions=computed(()=>managerNames.value.map(name=>({value:name,label:name})))
const searchText=value=>String(value??'').normalize('NFKC').toLocaleLowerCase('ru-RU').replace(/ё/g,'е').replace(/[^\p{L}\p{N}]+/gu,' ').trim()
const filteredGroups=computed(()=>{const tokens=searchText(query.value).split(/\s+/).filter(Boolean);if(!tokens.length)return groups.value;return groups.value.map(g=>({...g,phrases:(g.phrases||[]).filter(p=>{const hay=searchText([g.name,p.name,p.text,p.hotkey,...(p.managers||[])].join(' '));return tokens.every(t=>hay.includes(t))})})).filter(g=>g.phrases.length)})

function tab(path){router.push(`/admin/${path}`)}
async function load(){
  if(!session.isAdmin){router.replace('/more');return}
  loading.value=true
  try{
    overview.value=await api.adminOverview()
    users.value=overview.value.users||[];sections.value=overview.value.sections||[]
    if(section.value==='phrases'){const d=await api.adminPhrases();groups.value=d.groups||[];users.value=d.users||users.value}
    if(section.value==='users'){const d=await api.adminUsers();users.value=d.users||[];sections.value=d.sections||sections.value}
    if(section.value==='statuses'){const d=await api.adminStatuses();statuses.value=d.statuses||[]}
    if(section.value==='notifications'){const d=await api.adminNotificationJournal();notificationRows.value=d.rows||[]}
    if(section.value==='sla'){const d=await api.adminSlaSettings();users.value=d.users||users.value;Object.assign(slaForm,d.settings||{});slaForm.managerSchedules={...(d.settings?.managerSchedules||{})}}
  }catch(e){ui.toast(e.message,'error',7000)}finally{loading.value=false}
}
function openNewPhrase(){editingPhrase.value=null;Object.assign(phraseForm,{groupName:groupNames.value[0]||'Без раздела',name:'',text:'',hotkey:'',managers:[],attachments:[]});attachmentType.value='photo';attachmentInput.value='';moveTarget.value=phraseForm.groupName;phraseEditor.value=true}
function notifyPhraseChange(){try{localStorage.removeItem('seb-gun-v28-phrases')}catch{}window.dispatchEvent(new Event('crm:phrases-changed'))}
function openNewSection(){sectionName.value='';sectionEditor.value=true}
async function saveSection(){saving.value=true;try{const d=await api.createAdminPhraseGroup(sectionName.value);notifyPhraseChange();sectionEditor.value=false;await load();openNewPhrase();phraseForm.groupName=d.group?.name||sectionName.value;ui.toast('Раздел создан — добавьте первую фразу','ok')}catch(e){ui.toast(e.message,'error')}finally{saving.value=false}}
function openPhrase(p,g){editingPhrase.value={...p,groupName:g.name,index:(g.phrases||[]).findIndex(x=>x.id===p.id)};Object.assign(phraseForm,{groupName:g.name,name:p.name||'',text:p.text||'',hotkey:p.hotkey||'',managers:[...(p.managers||[])],attachments:[...(p.attachments||[])]});attachmentInput.value='';moveTarget.value=g.name;phraseEditor.value=true}
function phrasePayload(){return {groupName:phraseForm.groupName,name:phraseForm.name,text:phraseForm.text,hotkey:phraseForm.hotkey,managers:[...phraseForm.managers],attachments:[...phraseForm.attachments]}}
function addPhraseAttachment(){const token=normalizeVkAttachment(attachmentInput.value,attachmentType.value);if(!token)return ui.toast(`Не удалось найти код «${selectedAttachmentType.value.label}» в ссылке`,'error',5000);if(!phraseForm.attachments.includes(token))phraseForm.attachments.push(token);attachmentInput.value='';ui.toast('Вложение добавлено','ok',1200)}
function removePhraseAttachment(index){phraseForm.attachments.splice(index,1)}
async function savePhrase(){saving.value=true;try{if(editingPhrase.value)await api.updateAdminPhrase(editingPhrase.value.id,phrasePayload());else await api.createAdminPhrase(phrasePayload());notifyPhraseChange();ui.toast('Быстрая фраза сохранена','ok');phraseEditor.value=false;await load()}catch(e){ui.toast(e.message,'error')}finally{saving.value=false}}
async function movePhrase(id,payload){try{await api.moveAdminPhrase(id,payload);notifyPhraseChange();await load()}catch(e){ui.toast(e.message,'error')}}
async function moveEdited(){if(!editingPhrase.value||!moveTarget.value)return;await movePhrase(editingPhrase.value.id,{groupName:moveTarget.value,position:'end'});phraseEditor.value=false;ui.toast('Фраза перемещена','ok')}
async function removePhrase(){if(!editingPhrase.value||!confirm('Удалить эту быструю фразу?'))return;saving.value=true;try{await api.deleteAdminPhrase(editingPhrase.value.id);notifyPhraseChange();phraseEditor.value=false;await load()}catch(e){ui.toast(e.message,'error')}finally{saving.value=false}}
function toggleManager(name){const i=phraseForm.managers.indexOf(name);if(i>=0)phraseForm.managers.splice(i,1);else phraseForm.managers.push(name)}
function openUser(u){editingUser.value=u;Object.assign(userForm,{role:u.role||'manager',status:u.status||'active',color:u.color||'#2f7d55',sections:[...(u.sections||[])]});userEditor.value=true}
function toggleSection(name){const i=userForm.sections.indexOf(name);if(i>=0)userForm.sections.splice(i,1);else userForm.sections.push(name)}
async function saveUser(){saving.value=true;try{await api.updateAdminUser(editingUser.value.login||editingUser.value.email||editingUser.value.id,{...userForm,sections:[...userForm.sections]});ui.toast('Права пользователя сохранены','ok');userEditor.value=false;await load()}catch(e){ui.toast(e.message,'error')}finally{saving.value=false}}
async function saveStatus(row){row.saving=true;try{await api.updateAdminStatus(row.name,row.color);ui.toast(`Цвет «${row.name}» сохранён`,'ok')}catch(e){ui.toast(e.message,'error')}finally{row.saving=false}}
function journalDate(seconds){return seconds?new Date(Number(seconds)*1000).toLocaleString('ru-RU',{timeZone:'Europe/Moscow'}):'—'}
async function removeNotification(row){if(!confirm(`Удалить уведомление «${row.name}» из журнала?`))return;try{await api.deleteAdminNotificationJournal(row.id);notificationRows.value=notificationRows.value.filter(x=>x.id!==row.id);ui.toast('Уведомление удалено','ok')}catch(e){ui.toast(e.message,'error')}}
function toggleWorkDay(day,target=slaForm){const i=target.workDays.indexOf(day);if(i>=0)target.workDays.splice(i,1);else target.workDays.push(day)}
function scheduleFor(name){if(!slaForm.managerSchedules[name])slaForm.managerSchedules[name]={enabled:true,workDays:[...slaForm.workDays],workStart:slaForm.workStart,workEnd:slaForm.workEnd};return slaForm.managerSchedules[name]}
async function saveSla(){saving.value=true;try{const d=await api.saveAdminSlaSettings({...slaForm,workDays:[...slaForm.workDays],managerSchedules:{...slaForm.managerSchedules}});Object.assign(slaForm,d.settings||{});ui.toast('Регламент сохранён и применяется ко всем журналам','ok')}catch(e){ui.toast(e.message,'error',7000)}finally{saving.value=false}}
watch(section,()=>{query.value='';load()})
onMounted(load)
</script>

<template>
  <main class="page page-with-nav admin-page">
    <header class="page-header sticky-header"><div><small>BLUESALES · АДМИНКА</small><h1>Настройки</h1></div><button class="header-action" @click="router.push('/more')">×</button></header>
    <nav class="admin-tabs" aria-label="Разделы админки"><button :class="{active:section==='phrases'}" @click="tab('phrases')">⚡ Быстрые фразы</button><button :class="{active:section==='users'}" @click="tab('users')">👥 Пользователи</button><button :class="{active:section==='statuses'}" @click="tab('statuses')">🎨 CRM-статусы</button><button :class="{active:section==='sla'}" @click="tab('sla')">⏱ Регламент SLA</button><button :class="{active:section==='notifications'}" @click="tab('notifications')">🔔 Журнал</button></nav>
    <div v-if="loading" class="list-status"><span class="tiny-spinner"></span> Загружаю…</div>

    <template v-if="!loading&&section==='phrases'">
      <section class="toolbar-card admin-toolbar"><div class="search-control"><span>⌕</span><input v-model="query" placeholder="Название, раздел или текст фразы"></div><div class="admin-create-actions"><button class="primary-btn" @click="openNewPhrase">+ Фраза</button><button class="secondary-btn" @click="openNewSection">+ Раздел</button></div></section>
      <p class="admin-summary">{{overview?.phraseCount||0}} фраз · {{overview?.groupCount||0}} разделов</p>
      <section v-for="g in filteredGroups" :key="g.id||g.name" class="admin-group"><h3>{{g.name}} <b>{{g.phrases.length}}</b></h3><article v-for="(p,i) in g.phrases" :key="p.id" class="admin-phrase-row"><button class="phrase-open" @click="openPhrase(p,g)"><strong>{{p.name}}</strong><span>{{p.text||'Без текста'}}</span><small v-if="p.attachments?.length">📎 {{p.attachments.length}} · {{p.attachments.map(x=>attachmentMeta(x).icon).join(' ')}}</small><small v-if="p.managers?.length">{{p.managers.join(' · ')}}</small></button><div class="phrase-move"><button title="В начало" :disabled="i===0" @click="movePhrase(p.id,{groupName:g.name,position:'start'})">⇈</button><button title="Выше" :disabled="i===0" @click="movePhrase(p.id,{groupName:g.name,index:i-1})">↑</button><button title="Ниже" :disabled="i===g.phrases.length-1" @click="movePhrase(p.id,{groupName:g.name,index:i+1})">↓</button><button title="В конец" :disabled="i===g.phrases.length-1" @click="movePhrase(p.id,{groupName:g.name,position:'end'})">⇊</button></div></article></section>
    </template>

    <section v-if="!loading&&section==='users'" class="admin-card-list"><button v-for="u in users" :key="u.id||u.login" class="admin-user-row" @click="openUser(u)"><i :style="{background:u.color||'var(--accent)'}"></i><span><strong>{{u.name||u.login}}</strong><small>{{u.login}}</small></span><b :class="u.status==='blocked'?'blocked':'active-user'">{{u.status==='blocked'?'Заблокирован':'Активен'}}</b><em>{{u.role==='manager'?'Менеджер':'Администратор'}}</em></button></section>

    <section v-if="!loading&&section==='statuses'" class="admin-card-list"><article v-for="row in statuses" :key="row.name" class="status-admin-row"><i :style="{background:row.color||'#809087'}"></i><strong>{{row.name}}</strong><input v-model="row.color" type="color" :aria-label="`Цвет ${row.name}`"><button class="secondary-btn" :disabled="row.saving" @click="saveStatus(row)">{{row.saving?'…':'Сохранить'}}</button></article><p class="settings-hint">CRM-статусы берутся из BlueSales. Здесь можно задать их цвет в CRM.</p></section>

    <section v-if="!loading&&section==='sla'" class="sla-admin"><section class="settings-card"><h3>Общий регламент</h3><p class="settings-hint">Эти значения используются журналом лидов, веб-уведомлениями, Telegram и расчётом нарушений.</p><label>Рабочие дни</label><div class="weekday-picker"><button v-for="[day,label] in weekDays" :key="day" :class="{active:slaForm.workDays.includes(day)}" @click="toggleWorkDay(day)">{{label}}</button></div><div class="form-grid"><label>Начало дня<input v-model="slaForm.workStart" type="time"></label><label>Конец дня<input v-model="slaForm.workEnd" type="time"></label><label>Уведомить через, минут<input v-model.number="slaForm.notifyMinutes" type="number" min="1" max="240"></label><label>Нарушение через, минут<input v-model.number="slaForm.violationMinutes" type="number" min="1" max="1440"></label></div><label>Действие при нарушении<select v-model="slaForm.violationAction"><option value="journal">Зафиксировать в журнале нарушений</option><option value="journal_and_admin">Журнал и выделение в админке</option></select></label><label class="toggle-row"><input v-model="slaForm.notifyWeb" type="checkbox"><span>Веб-уведомление менеджеру</span></label><label class="toggle-row"><input v-model="slaForm.notifyTelegram" type="checkbox"><span>Telegram-уведомление менеджеру</span></label></section><section class="settings-card"><h3>Рабочий день менеджеров</h3><details v-for="u in users" :key="u.login||u.name" class="manager-schedule"><summary>{{u.name||u.login}} <span>▾</span></summary><div><label class="toggle-row"><input v-model="scheduleFor(u.name||u.login).enabled" type="checkbox"><span>Индивидуальный график</span></label><div class="weekday-picker"><button v-for="[day,label] in weekDays" :key="day" :class="{active:scheduleFor(u.name||u.login).workDays.includes(day)}" @click="toggleWorkDay(day,scheduleFor(u.name||u.login))">{{label}}</button></div><div class="form-grid"><label>Начало<input v-model="scheduleFor(u.name||u.login).workStart" type="time"></label><label>Конец<input v-model="scheduleFor(u.name||u.login).workEnd" type="time"></label></div></div></details></section><button class="primary-btn sla-save" :disabled="saving" @click="saveSla">{{saving?'Сохраняю…':'Сохранить регламент'}}</button></section>

    <section v-if="!loading&&section==='notifications'" class="admin-card-list admin-notification-list"><p class="admin-summary">Журнал лидов: {{notificationRows.length}}. Удалённая запись не появится повторно для того же входящего сообщения.</p><article v-for="row in notificationRows" :key="row.id" class="admin-notification-row"><button @click="router.push(`/dialogs/${row.peerId}`)"><strong>{{row.name}}</strong><span>{{row.snippet||'Входящее сообщение'}}</span><small>{{row.manager||'Менеджер не назначен'}}<template v-if="row.crmStatus"> · {{row.crmStatus}}</template></small><em>Получено: {{journalDate(row.receivedAt)}}<template v-if="row.status==='answered'"> · Отвечено: {{journalDate(row.answeredAt)}}</template></em></button><div class="journal-state"><b v-if="row.violation" class="violation-badge">Нарушение &gt; {{row.violationMinutes}} мин</b><b :class="row.status==='answered'?'answered-badge':'waiting-badge'">{{row.status==='answered'?'Отвечено':'Без ответа'}}</b></div><button class="danger-link admin-journal-delete" @click="removeNotification(row)">Удалить</button></article><div v-if="!notificationRows.length" class="empty-state"><b>Журнал пуст</b><span>Лиды появятся после синхронизации VK-диалогов.</span></div></section>
  </main>

  <Teleport to="body"><div v-if="phraseEditor" class="sheet-backdrop" @click.self="phraseEditor=false"><section class="bottom-sheet admin-editor-sheet"><header class="sheet-head"><div><small>{{editingPhrase?'РЕДАКТИРОВАНИЕ':'НОВАЯ ФРАЗА'}}</small><h3>Быстрая фраза</h3></div><button class="icon-circle" @click="phraseEditor=false">×</button></header><div class="admin-editor-scroll"><label>Раздел<input v-if="!editingPhrase" v-model="phraseForm.groupName" list="phrase-groups" placeholder="Название раздела"><b v-else>{{phraseForm.groupName}}</b></label><datalist id="phrase-groups"><option v-for="g in groupNames" :key="g" :value="g"/></datalist><label>Название<input v-model="phraseForm.name" placeholder="Название фразы"></label><label>Текст<textarea v-model="phraseForm.text" rows="7" placeholder="Текст и эмодзи, которые попадут в черновик 😊"></textarea></label><label>Горячая клавиша<input v-model="phraseForm.hotkey" placeholder="Например: привет"></label><label>Менеджеры<button type="button" class="select-sheet-trigger" @click="managersPicker=true"><span>{{phraseForm.managers.length?phraseForm.managers.join(', '):'Все менеджеры'}}</span><b>▾</b></button></label><fieldset class="phrase-attachment-editor"><legend>Вложения ВКонтакте</legend><div class="attachment-type-tabs"><button v-for="type in VK_ATTACHMENT_TYPES" :key="type.id" type="button" :class="{active:attachmentType===type.id}" @click="attachmentType=type.id">{{type.icon}} {{type.label}}</button></div><p class="settings-hint">Вставьте ссылку из ВК/BlueSales или готовый код. Вложение должно принадлежать той же группе ВК.</p><div class="attachment-add-row"><input v-model="attachmentInput" :placeholder="selectedAttachmentType.example" @keydown.enter.prevent="addPhraseAttachment"><button type="button" class="primary-btn" :disabled="!attachmentInput.trim()" @click="addPhraseAttachment">Добавить</button></div><div v-if="phraseForm.attachments.length" class="phrase-attachment-list"><span v-for="(token,index) in phraseForm.attachments" :key="token"><b>{{attachmentMeta(token).icon}} {{token}}</b><button type="button" title="Удалить вложение" @click="removePhraseAttachment(index)">×</button></span></div><p v-else class="settings-hint">Вложений пока нет. Текст и эмодзи сохраняются отдельно.</p></fieldset><div v-if="editingPhrase" class="explicit-move"><b>Переместить в другой раздел</b><select v-model="moveTarget"><option v-for="g in groupNames" :key="g">{{g}}</option></select><button class="secondary-btn" :disabled="moveTarget===phraseForm.groupName" @click="moveEdited">Переместить</button></div><button v-if="editingPhrase" class="danger-btn editor-danger" @click="removePhrase">Удалить фразу</button></div><footer class="sheet-actions"><button class="secondary-btn" @click="phraseEditor=false">Отмена</button><button class="primary-btn" :disabled="saving||!phraseForm.name.trim()" @click="savePhrase">{{saving?'Сохраняю…':'Сохранить'}}</button></footer></section></div></Teleport>

  <Teleport to="body"><div v-if="sectionEditor" class="sheet-backdrop" @click.self="sectionEditor=false"><section class="bottom-sheet compact-editor-sheet"><header class="sheet-head"><div><small>БЫСТРЫЕ ФРАЗЫ</small><h3>Новый раздел</h3></div><button class="icon-circle" @click="sectionEditor=false">×</button></header><div class="admin-editor-scroll"><label>Название раздела<input v-model="sectionName" placeholder="Например: ПРИВЕТСТВИЕ" @keydown.enter.prevent="sectionName.trim()&&saveSection()"></label><p class="settings-hint">После создания откроется форма первой фразы этого раздела.</p></div><footer class="sheet-actions"><button class="secondary-btn" @click="sectionEditor=false">Отмена</button><button class="primary-btn" :disabled="saving||!sectionName.trim()" @click="saveSection">{{saving?'Создаю…':'Создать раздел'}}</button></footer></section></div></Teleport>

  <Teleport to="body"><div v-if="userEditor" class="sheet-backdrop" @click.self="userEditor=false"><section class="bottom-sheet admin-editor-sheet"><header class="sheet-head"><div><small>ПОЛЬЗОВАТЕЛЬ</small><h3>{{editingUser?.name}}</h3></div><button class="icon-circle" @click="userEditor=false">×</button></header><div class="admin-editor-scroll"><p class="settings-hint">{{editingUser?.login}}</p><label>Роль</label><div class="segmented admin-role"><button :class="{active:userForm.role==='manager'}" @click="userForm.role='manager'">Менеджер</button><button :class="{active:userForm.role==='admin'}" @click="userForm.role='admin'">Админ</button><button :class="{active:userForm.role==='creator_admin'}" @click="userForm.role='creator_admin'">Создатель</button></div><label>Статус</label><div class="segmented two"><button :class="{active:userForm.status==='active'}" @click="userForm.status='active'">Активен</button><button :class="{active:userForm.status==='blocked'}" @click="userForm.status='blocked'">Заблокирован</button></div><label>Цвет менеджера<input v-model="userForm.color" type="color"></label><fieldset><legend>Доступ к разделам</legend><button v-for="name in sections" :key="name" type="button" class="check-row" @click="toggleSection(name)"><span class="check-box" :class="{checked:userForm.sections.includes(name)}">{{userForm.sections.includes(name)?'✓':''}}</span>{{name}}</button></fieldset><a v-if="editingUser?.blueSalesEditUrl" class="secondary-btn link-btn" :href="editingUser.blueSalesEditUrl" target="_blank" rel="noreferrer">Открыть в BlueSales</a></div><footer class="sheet-actions"><button class="secondary-btn" @click="userEditor=false">Отмена</button><button class="primary-btn" :disabled="saving" @click="saveUser">{{saving?'Сохраняю…':'Сохранить'}}</button></footer></section></div></Teleport>
  <MultiFilterSheet :open="managersPicker" title="Менеджеры" :options="managerOptions" v-model="phraseForm.managers" @apply="managersPicker=false" @close="managersPicker=false"/>
</template>
